name: 'Application Deploy'
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Application Publish]
    branches: 
      - main
    types:
      - completed
jobs:
  publish:
    runs-on: 'ubuntu-20.04'
    environment: 'dev'
    steps:
      # - uses: actions/checkout@v3
      - name: Application Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOSTS }}
          username: azureuser
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            rm -rf ~/application
            mkdir ~/application

            bash -c "cat > /home/${HOME_USER}/application/.npmrc" <<EOF
            @softchoice-corp:registry=https://npm.pkg.github.com
            EOF

            sudo chown -R ${HOME_USER}:${HOME_USER} /home/${HOME_USER}/application

            pushd /home/${HOME_USER}/application
            npm install @softchoice-corp/omes-application
            popd

            pushd /home/${HOME_USER}/application/node_modules/@softchoice-corp/omes-application
            sudo pkill -P $(ps -ef | grep node\ ./src/index.js | head -1 | awk '{print $2}')
            nohup npm run start &
            popd
