name: 'Application Publish'
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Application Build]
    branches: 
      - main
    types:
      - completed
jobs:
  publish:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: 'softchoice-corp'
      - name: Bump package
        uses: commitizen-tools/commitizen-action@master
        id: pkg
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.pkg.outputs.version }}"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
