name: 'Application Deploy'
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Application Publish]
    branches: 
      - main
    types:
      - completed
jobs:
  publish:
    runs-on: 'ubuntu-20.04'
    environment: 'dev'
    steps:
      # - uses: actions/checkout@v3
      - name: Application Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOSTS }}
          username: azureuser
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            whoami
            echo hello
