name: 'Application Build'
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'package*.json'
      # Remove after testing
      - '**/*'
jobs:
  build:
    runs-on: 'ubuntu-20.04'
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test
  publish:
    needs: build
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # TESTING
      # - name: Bump package
      #   uses: commitizen-tools/commitizen-action@master
      #   id: pkg
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Print Version
      #   run: echo "Bumped to version ${{ steps.pkg.outputs.version }}"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
